version: '3'

services:
  dbDev:
    image: postgres
    env_file:
      - ./.env.dev
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    networks:
      - dbNetwork
      
  pgadminDev:
    image: dpage/pgadmin4
    env_file:
      - ./.env.dev
    ports:
      - "16543:80"
    depends_on:
      - dbDev
    networks:
      - dbNetwork

networks: 
  dbNetwork:
    driver: bridge

volumes:
  postgres_data: