version: '3'

services:
  chat-server:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
    - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
    networks:
      - postgres-network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - chat-server
    networks:
      - postgres-network

  certbot:
    image: certbot/certbot
    volumes:  
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
    networks:
      - postgres-network

  postgres:
    image: postgres
    env_file:
      - ./.env.prod
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.prod
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume: