version: '3'

services:
  chat-server:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
    - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
    networks:
      - postgres-network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - chat-server
    networks:
      - postgres-network

  postgres:
    image: postgres
    env_file:
      - ./.env.prod
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.prod
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume: