version: '3'

services:
  postgres-dev:
    image: postgres
    env_file:
      - ./.env.dev
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    networks:
      - db-network-dev
      
  pgadmin-dev:
    image: dpage/pgadmin4
    env_file:
      - ./.env.dev
    ports:
      - "16543:80"
    depends_on:
      - postgres-dev
    networks:
      - db-network-dev

networks: 
  db-network-dev:
    driver: bridge

volumes:
  postgres_data: