# Generated by Django 4.0.4 on 2022-04-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Nome do usuário'),
        ),
    ]
