# Generated by Django 4.0.4 on 2022-04-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_confirmation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
